services:
  - type: web
    name: dekhla-server
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build --filter game-engine && pnpm build --filter server
    startCommand: node apps/server/dist/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: "*"
