services:
  - type: web
    name: dekhla-server
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build --filter game-engine && pnpm run build --filter server
    startCommand: node apps/server/dist/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: "*"
